class RegionOfOrigin < ActiveHash::Base
  self.data = [
    { id: 1, region_of_origin: "---" },
    { id: 2, region_of_origin: "北海道" },
    { id: 3, region_of_origin: "青森県" },
    { id: 4, region_of_origin: "岩手県" },
    { id: 5, region_of_origin: "宮城県" },
    { id: 6, region_of_origin: "秋田県" },
    { id: 7, region_of_origin: "山形県" },
    { id: 8, region_of_origin: "福島県" },
    { id: 9, region_of_origin: "茨城県" },
    { id: 10, region_of_origin: "栃木県" },
    { id: 11, region_of_origin: "群馬県" },
    { id: 12, region_of_origin: "埼玉県" },
    { id: 13, region_of_origin: "千葉県" },
    { id: 14, region_of_origin: "東京都" },
    { id: 15, region_of_origin: "神奈川県" },
    { id: 16, region_of_origin: "新潟県" },
    { id: 17, region_of_origin: "富山県" },
    { id: 18, region_of_origin: "石川県" },
    { id: 19, region_of_origin: "福井県" },
    { id: 20, region_of_origin: "山梨県" },
    { id: 21, region_of_origin: "長野県" },
    { id: 22, region_of_origin: "岐阜県" },
    { id: 23, region_of_origin: "静岡県" },
    { id: 24, region_of_origin: "愛知県" },
    { id: 25, region_of_origin: "三重県" },
    { id: 26, region_of_origin: "滋賀県" },
    { id: 27, region_of_origin: "京都府" },
    { id: 28, region_of_origin: "大阪府" },
    { id: 29, region_of_origin: "兵庫県" },
    { id: 30, region_of_origin: "奈良県" },
    { id: 31, region_of_origin: "和歌山県" },
    { id: 32, region_of_origin: "鳥取県" },
    { id: 33, region_of_origin: "島根県" },
    { id: 34, region_of_origin: "岡山県" },
    { id: 35, region_of_origin: "広島県" },
    { id: 36, region_of_origin: "山口県" },
    { id: 37, region_of_origin: "徳島県" },
    { id: 38, region_of_origin: "香川県" },
    { id: 39, region_of_origin: "愛媛県" },
    { id: 40, region_of_origin: "高知県" },
    { id: 41, region_of_origin: "福岡県" },
    { id: 42, region_of_origin: "佐賀県" },
    { id: 43, region_of_origin: "長崎県" },
    { id: 44, region_of_origin: "熊本県" },
    { id: 45, region_of_origin: "大分県" },
    { id: 46, region_of_origin: "宮崎県" },
    { id: 47, region_of_origin: "鹿児島県" },
    { id: 48, region_of_origin: "沖縄県" }
  ]
  include ActiveHash::Associations
  has_many :items
end